/**
 * Intent config: synonyms, actions, targets, mapping rules
 * Pipeline: normalize → synonyms → extract action+target → score → best intent
 */

export type Action = "suggest" | "view" | "check" | "book" | "greet" | "fallback";

export type Target =
  | "coffee"
  | "freeze"
  | "tea"
  | "phindi"
  | "juice"
  | "others_drink"
  | "drink"
  | "bakery_savory"
  | "bakery_sweet"
  | "bakery"
  | "topping"
  | "menu"
  | "order"
  | "promotion"
  | "reservation"
  | "table"
  | "nearest_store"
  | "drink_pairing_combo"
  | "drink_pairing_cake"
  | "drink_pairing_combo_and_cake"
  | "combo"
  | "combo_tea"
  | "combo_coffee"
  | "combo_phindi"
  | "points"
  | "faq"
  | "greeting";

/** Từ đồng nghĩa: chuỗi normalized (không dấu) -> chuỗi chuẩn. Pipeline normalize trước rồi mới replace. */
export const SYNONYMS: [string, string][] = [
  ["co goi y nao khong", "suggest"],
  ["co goi y khong", "suggest"],
  ["co mon nao ngon khong", "suggest"],
  ["co mon nao ngon", "suggest"],
  ["cho xin goi y", "suggest"],
  ["cho minh goi y", "suggest"],
  ["cho em goi y", "suggest"],
  ["chua biet chon gi", "suggest"],
  ["chua biet uong gi", "suggest"],
  ["goi y minh mon de uong", "suggest"],
  ["goi y mon de uong", "suggest"],
  ["mon nao de uong", "suggest"],
  ["mon nao ngon", "suggest"],
  ["uong gi ngon", "suggest"],
  ["an gi ngon", "suggest"],
  ["muon thu", "suggest"],
  ["muon uong gi", "suggest"],
  ["muon an gi", "suggest"],
  ["ban goi y gi", "suggest"],
  ["ban goi y", "suggest"],
  ["hay goi y cho toi 1 mon bat ki", "suggest"],
  ["hay goi y cho toi 1 mon bat ky", "suggest"],
  ["goi y cho toi 1 mon bat ki", "suggest"],
  ["goi y cho toi 1 mon bat ky", "suggest"],
  ["tu van giup minh", "suggest"],
  ["tu van giup em", "suggest"],
  ["tu van giup toi", "suggest"],
  ["tu van cho minh", "suggest"],
  ["tu van cho em", "suggest"],
  ["tu van cho toi", "suggest"],
  ["tu van mon ngon", "suggest"],
  ["tu van do uong", "suggest"],
  ["tu van thuc uong", "suggest"],
  ["goi y do uong", "suggest"],
  ["goi y thuc uong", "suggest"],
  ["goi y mon ngon", "suggest"],
  ["goi y mon nao ngon", "suggest"],
  ["gioi thieu mon ngon", "suggest"],
  ["gioi thieu mon signature", "suggest"],
  ["gioi thieu mon dac trung", "suggest"],
  ["co mon nao nen thu", "suggest"],
  ["nen thu mon nao", "suggest"],
  ["nen thu gi", "suggest"],
  ["nen goi gi", "suggest"],
  ["nen chon gi", "suggest"],
  ["hom nay nen uong gi", "suggest"],
  ["hom nay nen an gi", "suggest"],
  ["uong gi bay gio", "suggest"],
  ["an gi bay gio", "suggest"],
  ["best seller la gi", "suggest"],
  ["mon nao ban chay", "suggest"],
  ["mon nao best seller", "suggest"],
  ["mon nao signature", "suggest"],
  ["mon nao dac trung", "suggest"],
  ["hay goi y", "suggest"],
  ["goi y nao", "suggest"],
  ["goi y mon", "suggest"],
  ["goi y 1 mon", "suggest"],
  ["goi y", "suggest"],
  ["de xuat", "suggest"],
  ["recommend", "suggest"],
  ["recommend giup", "suggest"],
  ["recommend cho minh", "suggest"],
  ["recommend cho em", "suggest"],
  ["recommend cho toi", "suggest"],
  ["recommend mon", "suggest"],
  ["suggestion", "suggest"],
  ["thi sao", "suggest"],
  ["the nao", "suggest"],
  ["nao ngon", "suggest"],
  ["nen uong gi", "suggest"],
  ["nen an gi", "suggest"],
  ["nhung mon khac", "suggest"],
  ["mon khac", "suggest"],
  ["the con", "suggest"],
  ["neu la", "suggest"],
  ["co gi ngon", "suggest"],
  ["gi ngon", "suggest"],
  // --- view / check ---
  ["tim cho toi", "view"],
  ["tim cho minh", "view"],
  ["tim giup", "view"],
  ["tim", "view"],
  ["co gi", "view"],
  ["co nhung gi", "view"],
  ["co combo hay loai banh nao phu hop", "view"],
  ["co combo hay banh nao phu hop", "view"],
  ["co combo nao hoac banh nao phu hop voi no", "view"],
  ["combo nao hoac banh nao phu hop", "view"],
  ["combo nao phu hop", "view"],
  ["banh nao phu hop", "view"],
  ["goi kem combo gi", "view"],
  ["goi kem banh gi", "view"],
  ["di kem combo gi", "view"],
  ["di kem banh gi", "view"],
  ["nen goi kem combo gi", "view"],
  ["nen goi kem banh gi", "view"],
  ["nen an kem banh gi", "view"],
  ["nen uong kem combo gi", "view"],
  ["ghep voi combo gi", "view"],
  ["ghep voi banh gi", "view"],
  ["phoi voi combo gi", "view"],
  ["phoi voi banh gi", "view"],
  ["ket hop voi combo gi", "view"],
  ["ket hop voi banh gi", "view"],
  ["match voi combo gi", "view"],
  ["match voi banh gi", "view"],
  ["pair voi combo gi", "view"],
  ["pair voi banh gi", "view"],
  ["pairing voi combo", "view"],
  ["pairing voi banh", "view"],
  ["hop voi combo nao", "view"],
  ["hop voi banh nao", "view"],
  ["combo nao hop", "view"],
  ["banh nao hop", "view"],
  ["combo nao di cung", "view"],
  ["banh nao di cung", "view"],
  ["combo nao an cung", "view"],
  ["banh nao an cung", "view"],
  ["combo nao uong cung", "view"],
  ["banh nao uong cung", "view"],
  ["mon nay nen di kem gi", "view"],
  ["nuoc nay nen di kem gi", "view"],
  ["mon nay hop gi", "view"],
  ["nuoc nay hop gi", "view"],
  ["mon nay ghep gi", "view"],
  ["nuoc nay ghep gi", "view"],
  ["mon nay ket hop voi gi", "view"],
  ["nuoc nay ket hop voi gi", "view"],
  ["mon nay an kem gi", "view"],
  ["nuoc nay an kem gi", "view"],
  ["mon nay uong kem gi", "view"],
  ["nuoc nay uong kem gi", "view"],
  ["mon nay dung voi gi", "view"],
  ["nuoc nay dung voi gi", "view"],
  ["mon nay nen an cung gi", "view"],
  ["nuoc nay nen an cung gi", "view"],
  ["mon nay nen uong cung gi", "view"],
  ["nuoc nay nen uong cung gi", "view"],
  ["mon nay di chung voi gi", "view"],
  ["nuoc nay di chung voi gi", "view"],
  ["mon nay hop voi combo va banh nao", "view"],
  ["nuoc nay hop voi combo va banh nao", "view"],
  ["mon nay nen an kem combo hay banh gi", "view"],
  ["nuoc nay nen an kem combo hay banh gi", "view"],
  ["mon nay nen uong kem combo hay banh gi", "view"],
  ["nuoc nay nen uong kem combo hay banh gi", "view"],
  ["phu hop voi no", "view"],
  ["phu hop voi nuoc", "view"],
  ["phu hop voi mon", "view"],
  ["xem thu", "view"],
  ["cho xem", "view"],
  ["cho minh xem", "view"],
  ["cho minh biet", "view"],
  ["cho em biet", "view"],
  ["cho toi biet", "view"],
  ["co the cho minh biet", "view"],
  ["co the cho em biet", "view"],
  ["co the cho toi biet", "view"],
  ["xin cho biet", "view"],
  ["cho hoi", "view"],
  ["cho minh hoi", "view"],
  ["cho em hoi", "view"],
  ["cho toi hoi", "view"],
  ["xin hoi", "view"],
  ["minh muon hoi", "view"],
  ["em muon hoi", "view"],
  ["toi muon hoi", "view"],
  ["minh can biet", "view"],
  ["em can biet", "view"],
  ["toi can biet", "view"],
  ["giai dap", "view"],
  ["muon xem", "view"],
  ["muon biet", "view"],
  ["muon tim", "view"],
  ["tham khao", "view"],
  ["xem giup", "view"],
  ["xem thong tin", "view"],
  ["tim hieu", "view"],
  ["xem", "view"],
  ["tra cuu giup", "check"],
  ["tra cuu", "check"],
  ["check giup", "check"],
  ["check", "check"],
  ["xem trang thai", "check"],
  ["kiem tra", "view"],
  ["co gi", "view"],
  ["dat ban", "book_table"],
  ["dat cho", "book_table"],
  ["giu ban", "book_table"],
  ["giu cho", "book_table"],
  ["book ban", "book_table"],
  ["reserve", "book_table"],
  ["reservation", "book_table"],
  ["dat", "book"],
  ["xin chao", "greet"],
  ["chao", "greet"],
  ["hello", "greet"],
  ["hi", "greet"],
  ["hey", "greet"],
  ["good morning", "greet"],
  ["good afternoon", "greet"],
  ["good evening", "greet"],
  ["shop oi", "greet"],
  ["quan oi", "greet"],
  ["ban oi", "greet"],
];

/** Target patterns: từ/cụm normalized (không dấu) → target. Pipeline normalize trước rồi mới match. */
export const TARGET_PATTERNS: { target: Target; patterns: string[]; priority: number }[] = [
  // --- bakery ---
  {
    target: "bakery_savory",
    patterns: [
      "banh man", "banh mi", "banh mi que", "croissant", "sandwich",
      "banh man nao", "goi y banh man", "banh kep", "banh nong", "banh an sang", "banh man de an sang",
      "banh sandwich", "croissant man", "banh mi kep ga xe", "banh kep ga xe", "ga xe",
      "banh mi que bo toi", "bo toi", "croissant bo", "croissant ham cheese", "ham cheese",
      "sandwich ca ngu mayo", "ca ngu mayo", "sandwich ca ngu",
    ],
    priority: 10,
  },
  {
    target: "bakery_sweet",
    patterns: [
      "banh ngot", "banh kem", "banh bong lan", "cake", "cheesecake", "tiramisu", "brownie", "muffin",
      "banh ngot nao", "goi y banh ngot", "banh ngot nao ngon", "su kem", "mousse",
      "red velvet", "dessert", "banh trang mieng", "banh an vat ngot", "banh ngot de an sang",
      "banh bong lan trung muoi", "trung muoi", "banh brownie socola", "brownie socola",
      "banh cheesecake viet quat", "cheesecake viet quat", "banh mousse chanh day", "mousse chanh day",
      "banh muffin viet quat", "muffin viet quat", "banh opera", "opera", "banh phomai nhat",
      "phomai nhat", "banh red velvet", "banh su kem socola", "su kem socola", "banh su kem vanilla",
      "su kem vanilla", "banh tart trung", "tart trung", "banh tiramisu",
    ],
    priority: 10,
  },
  {
    target: "bakery",
    patterns: [
      "banh", "con banh", "mon banh", "goi y banh", "mon an", "snack", "do an vat", "an kem",
      "an nhe", "do an", "do ngot", "mon an nhe", "mon an kem nuoc",
    ],
    priority: 5,
  },
  // --- drinks (cụ thể) ---
  {
    target: "coffee",
    patterns: [
      "ca phe", "cafe", "coffee", "capuchino", "cappuccino", "latte", "americano", "espresso",
      "bac xiu", "ca phe sua", "ca phe den", "ca phe da", "ca phe nong", "uong ca phe", "mon ca phe",
      "ca phe nao", "ca phe nao ngon", "ca phe nao dam", "ca phe dam", "mon ca phe nao",
      "cafe sua da", "cafe den", "cafe den da", "cafe nong", "cafe sua nong", "ca phe sua da",
      "ca phe sua nong", "mocha", "macchiato", "iced coffee", "hot coffee", "caramel macchiato",
      "phin", "phin den", "phin sua", "phin den da", "phin den nong", "phin sua da", "phin sua nong",
      "bac xiu da", "bac xiu nong", "americano da", "americano nong", "cappuccino da", "latte da",
      "mocha da", "cafe phin", "ca phe phin", "macchiato caramel",
    ],
    priority: 9,
  },
  {
    target: "freeze",
    patterns: [
      "freeze", "da xay", "da say",
      "uong freeze", "mon freeze", "freeze nao", "da xay nao ngon", "frappe", "ice blended",
      "blended", "cookies da xay", "socola da xay", "choco da xay", "caramel da xay",
      "caramel phin freeze", "classic phin freeze", "chocolate freeze", "cookies cream",
      "cookies and cream", "freeze tra xanh", "tra xanh freeze", "phin freeze",
      "freeze socola", "freeze caramel",
    ],
    priority: 9,
  },
  {
    target: "tea",
    patterns: [
      "tra", "tea", "tra dao", "tra vai",
      "tra xanh", "tra sen", "uong tra", "mon tra", "tra nao", "tra nao ngon", "tra thanh nhe",
      "mon tra nao", "fruit tea", "green tea", "tra hoa qua", "tra sen vang", "sen vang",
      "tra thach dao", "thach dao", "tra thach vai", "thach vai", "tra thanh dao",
      "thanh dao", "tra xanh dau do", "dau do",
    ],
    priority: 9,
  },
  {
    target: "phindi",
    patterns: [
      "phindi", "phin di", "uong phindi", "mon phindi", "phindi nao",
      "phindi choco", "choco phindi", "phindi hanh nhan", "hanh nhan", "phindi kem sua",
      "kem sua phindi", "phindi kem", "phindi sua",
    ],
    priority: 9,
  },
  {
    target: "juice",
    patterns: [
      "nuoc ep", "juice", "nuoc cam",
      "uong nuoc ep", "mon nuoc ep", "nuoc ep nao", "cam ep", "ep cam",
      "dua hau ep", "ep dua hau", "oi ep", "ep oi", "nuoc trai cay", "fruit juice", "fresh juice",
      "nuoc ep cam", "nuoc ep dua hau", "nuoc ep oi",
    ],
    priority: 9,
  },
  {
    target: "topping",
    patterns: [
      "topping", "thach", "tran chau", "tran chau den", "pearl", "add on",
      "them topping", "topping nao", "goi y tran chau",
      "pudding", "jelly", "thach trai cay", "fruit jelly", "jelly trai cay",
    ],
    priority: 10,
  },
  {
    target: "others_drink",
    patterns: [
      "nuoc khac", "mon nuoc khac", "nuoc uong khac",
      "cacao", "socola", "chocolate", "chocolate da", "chocolate nong", "socola da", "socola nong",
      "cacao da", "cacao nong", "chanh da vien", "chanh da xay", "chanh day da vien",
      "chanh day", "tac da vien", "nuoc chanh", "nuoc tac",
    ],
    priority: 5,
  },
  {
    target: "drink",
    patterns: [
      "mon nuoc", "do uong", "thuc uong", "nuoc uong", "thuc an uong",
      "mon ngot", "ngot ngot", "mon de uong", "mon giong", "mon nao giong",
      "mon bat ki", "mon bat ky", "1 mon bat ki", "1 mon bat ky", "goi y 1 mon",
      "phu hop voi mua he", "mon phu hop mua he", "mua he", "thuc uong nao", "do uong nao", "u gi",
      "uong mon gi", "nuoc nao ngon", "goi nuoc gi", "khat nuoc uong gi", "mon mat", "mon thanh mat",
      "thuc uong mat", "nuoc mat", "do uong mat", "mon khac", "nhung mon khac", "them mon",
      "goi y mon khac", "them 1 mon khac", "mon nao khac", "goi y 1 mon khac",
    ],
    priority: 4,
  },
  // --- menu & order ---
  {
    target: "menu",
    patterns: [
      "menu", "thuc don", "thuc don co gi", "gia", "gia ca", "bang gia", "gia bao nhieu",
      "bao nhieu tien", "xem menu", "co menu khong", "list mon", "danh sach mon",
      "menu hien tai", "menu quan", "menu online", "full menu", "bang menu", "thuc don hom nay",
      "thuc don hien tai", "menu gia", "xem bang gia", "xem thuc don", "co mon gi",
      "ban gi", "quan ban gi", "co nhung mon nao", "co do uong gi", "co banh gi",
      "co gi de uong", "co gi de an", "xem mon", "xem do uong", "xem cac mon",
      "co gi hot", "co gi signature",
    ],
    priority: 7,
  },
  {
    target: "order",
    patterns: [
      "don hang", "order", "don", "trang thai don", "theo doi don", "don cua toi", "don da dat",
      "kiem tra don", "don minh dat", "don em dat", "ma don", "ma order", "tracking don", "track don",
      "tra cuu don", "check don", "don toi dau roi", "don den dau roi", "don dang o dau", "kiem tra ma don",
      "don cua minh", "don cua em", "don cua toi", "ma van don", "don thanh toan roi chua",
      "don co xac nhan chua", "order cua toi den dau roi", "xem don hang", "theo doi order",
    ],
    priority: 8,
  },
  // --- promotion ---
  {
    target: "promotion",
    patterns: [
      "khuyen mai", "uu dai", "sale", "discount", "giam gia", "ma giam gia", "voucher", "coupon",
      "chuong trinh khuyen mai", "co khuyen mai khong", "co uu dai khong", "dang giam gia",
      "km", "deal", "deal hot", "mua 1 tang 1", "buy 1 get 1", "freeship", "ma uu dai",
      "voucher hien co", "khuyen mai hom nay", "khuyen mai thang nay", "uu dai thanh vien", "deal ngon",
      "flash sale", "ma coupon", "voucher giam gia", "code giam gia", "code uu dai",
      "dang co event gi", "chuong trinh nao hot", "sale hom nay", "co deal nao ngon",
    ],
    priority: 8,
  },
  // --- reservation & table ---
  {
    target: "reservation",
    patterns: [
      "dat ban", "dat cho", "dat truoc", "book", "booking", "giu cho", "dat cho truoc", "giu ban",
      "reserve ban", "reservation", "dat cho ngoi", "hen cho", "dat vi tri", "giu vi tri",
      "book table", "reserve table", "dat ban online", "dat cho online",
    ],
    priority: 8,
  },
  {
    target: "table",
    patterns: [
      "ban trong", "con ban", "co ban khong", "co cho khong", "dat ban cho", "co cho ngoi khong",
      "con cho ngoi", "het ban chua", "quan dong khong", "ban con trong khong", "ban 2 nguoi",
      "ban 4 nguoi", "con ghe khong", "con cho cho 2 nguoi khong", "con cho cho 4 nguoi khong",
      "gio nay con ban khong", "chi nhanh nay con ban khong", "quan co dong khong",
    ],
    priority: 8,
  },
  // --- store & delivery ---
  {
    target: "nearest_store",
    patterns: [
      "quan gan nhat", "quan gan minh", "quan co vi tri gan nhat", "vi tri gan nhat", "tim quan gan",
      "cua hang gan", "cua hang gan nhat", "gan nhat", "chi nhanh", "co chi nhanh nao", "dia chi",
      "dia chi cua hang", "o dau", "quan o dau", "cua hang o dau", "co ship khong", "ship", "giao hang",
      "delivery", "gan day co quan", "quan nao gan", "branch", "store", "google map", "map",
      "chi duong", "duong di", "chi nhanh nao gan", "co quan nao gan day", "xung quanh day",
      "khu vuc nay", "xa khong", "dia diem", "toa do", "vi tri cua hang", "address",
      "chi nhanh gan toi", "chi nhanh gan em", "chi nhanh gan minh",
    ],
    priority: 8,
  },
  // --- drink_pairing (follow-up combo/bánh theo món nước - priority cao để match trước combo/bakery) ---
  {
    target: "drink_pairing_combo_and_cake",
    patterns: [
      "combo hay banh", "combo va banh", "combo hay loai banh", "combo nao va banh nao",
      "combo nao hoac banh nao", "combo nao hoac banh nao phu hop", "phu hop voi no",
      "combo hay loai banh nao phu hop", "co combo hay banh nao phu hop", "co combo hay loai banh nao phu hop",
      "co combo nao va banh nao hop", "combo va banh nao hop voi mon", "combo va banh",
      "combo hay banh nao phu hop voi nuoc", "loai banh nao phu hop voi nuoc",
      "combo hoac banh phu hop", "banh nao phu hop voi no", "uong mon nay kem combo hay banh gi",
      "mon nay hop combo hay banh gi", "nuoc nay hop combo hay banh gi", "mon nay ghep combo hay banh gi",
      "nuoc nay ghep combo hay banh gi", "mon nay nen goi kem combo hay banh gi",
      "nuoc nay nen goi kem combo hay banh gi", "mon nay nen phoi voi combo hay banh gi",
      "nuoc nay nen phoi voi combo hay banh gi", "pairing combo va banh", "combo va banh di kem",
      "combo va banh nao di cung mon nay", "combo va banh nao di cung nuoc nay",
      "mon nay hop voi combo va banh nao", "nuoc nay hop voi combo va banh nao",
      "mon nay nen an kem combo hay banh gi", "nuoc nay nen an kem combo hay banh gi",
      "mon nay nen uong kem combo hay banh gi", "nuoc nay nen uong kem combo hay banh gi",
      "mon nay an kem gi", "nuoc nay an kem gi", "mon nay uong kem gi", "nuoc nay uong kem gi",
      "mon nay dung voi gi", "nuoc nay dung voi gi", "mon nay nen an cung gi", "nuoc nay nen an cung gi",
      "mon nay nen uong cung gi", "nuoc nay nen uong cung gi", "mon nay di chung voi gi", "nuoc nay di chung voi gi",
    ],
    priority: 15,
  },
  {
    target: "drink_pairing_combo",
    patterns: [
      "combo hop voi nuoc", "combo hop voi mon", "combo phu hop voi mon", "combo phu hop voi nuoc",
      "mon nay combo", "nuoc nay combo", "mon nay co combo", "nuoc nay co combo",
      "mon nay di voi combo", "nuoc nay di voi combo", "mon nay di kem combo",
      "combo nao hop voi mon nay", "combo nao hop voi nuoc nay",
      "combo phu hop voi mon vua goi y", "combo phu hop voi nuoc vua chon",
      "uong mon nay kem combo nao", "mon nay ghep combo gi", "nuoc nay ghep combo gi",
      "mon nay nen di kem combo nao", "nuoc nay nen di kem combo nao", "mon nay nen goi kem combo nao",
      "nuoc nay nen goi kem combo nao", "mon nay ket hop combo nao", "nuoc nay ket hop combo nao",
      "mon nay phoi voi combo nao", "nuoc nay phoi voi combo nao", "combo nao di cung mon nay",
      "combo nao di cung nuoc nay", "combo nao match mon nay", "combo nao match nuoc nay",
      "pairing combo", "goi combo di kem", "combo di kem mon nay", "combo di kem nuoc nay",
      "mon nay an kem combo nao", "nuoc nay an kem combo nao", "mon nay dung voi combo nao",
      "nuoc nay dung voi combo nao", "mon nay nen an cung combo nao", "nuoc nay nen an cung combo nao",
      "mon nay nen uong cung combo nao", "nuoc nay nen uong cung combo nao",
    ],
    priority: 14,
  },
  {
    target: "drink_pairing_cake",
    patterns: [
      "banh hop voi nuoc", "banh hop voi mon", "banh phu hop voi mon", "banh phu hop voi nuoc",
      "mon nay banh", "nuoc nay banh", "mon nay di kem banh", "nuoc nay di kem banh",
      "mon nay di voi banh", "uong mon nay kem banh", "banh nao hop voi mon nay",
      "co banh nao hop voi", "co loai banh nao phu hop", "an banh gi kem mon nay",
      "mon nay ghep banh gi", "nuoc nay ghep banh gi", "mon nay nen an kem banh nao",
      "nuoc nay nen an kem banh nao", "mon nay nen goi kem banh nao", "nuoc nay nen goi kem banh nao",
      "mon nay ket hop banh nao", "nuoc nay ket hop banh nao", "mon nay phoi voi banh nao",
      "nuoc nay phoi voi banh nao", "banh nao di cung mon nay", "banh nao di cung nuoc nay",
      "banh nao match mon nay", "banh nao match nuoc nay", "pairing banh", "banh di kem mon nay",
      "banh di kem nuoc nay", "mon nay an kem banh gi", "nuoc nay an kem banh gi",
      "mon nay dung voi banh nao", "nuoc nay dung voi banh nao", "mon nay nen an cung banh nao",
      "nuoc nay nen an cung banh nao", "mon nay nen uong cung banh nao", "nuoc nay nen uong cung banh nao",
    ],
    priority: 14,
  },
  // --- combo (cụ thể trước) ---
  {
    target: "combo_tea",
    patterns: [
      "combo tra", "tra co combo", "combo tra co gi", "combo tra co nhung gi", "combo tra co mon gi",
      "combo tra nao", "tra co combo nao", "set tra", "goi tra combo", "combo uong tra", "combo danh cho tra",
    ],
    priority: 11,
  },
  {
    target: "combo_coffee",
    patterns: [
      "combo ca phe", "ca phe co combo", "combo ca phe co gi", "combo ca phe co nhung gi",
      "combo ca phe co mon gi", "combo ca phe nao", "cafe co combo", "set ca phe",
      "goi ca phe combo", "combo uong ca phe",
    ],
    priority: 11,
  },
  {
    target: "combo_phindi",
    patterns: [
      "combo phindi", "phindi co combo", "combo phindi co gi", "combo phindi co nhung gi",
      "phindi co combo gi", "combo phindi nao", "set phindi", "goi phindi combo", "combo uong phindi",
    ],
    priority: 11,
  },
  {
    target: "combo",
    patterns: [
      "combo", "combo nao", "co combo", "co combo nao", "goi combo", "uu dai combo", "combo mon",
      "set combo", "combo co gi", "co combo mon gi", "set", "goi uu dai", "combo nao ngon",
      "set tiet kiem", "goi tiet kiem", "phan combo", "bo combo", "combo deal", "combo tiet kiem",
      "combo uu dai", "combo nao nen thu", "combo nao ban chay", "combo signature",
      "combo hot", "combo tot nhat", "combo goi y", "combo nao hop voi toi",
    ],
    priority: 8,
  },
  // --- points ---
  {
    target: "points",
    patterns: [
      "tich diem", "diem tich luy", "doi diem", "quy doi diem", "chuong trinh thanh vien",
      "the thanh vien", "app tich diem", "diem thuong", "co tich diem khong", "hoi vien",
      "member", "membership", "reward", "rewards", "loyalty", "point", "point tich luy",
      "diem hoi vien", "uu dai hoi vien", "doi qua", "qua tang thanh vien", "voucher cua toi",
      "voucher cua em", "voucher cua minh", "kiem tra diem", "xem diem", "diem con bao nhieu",
      "co bao nhieu diem", "da du diem chua", "tich duoc bao nhieu diem",
    ],
    priority: 8,
  },
  // --- faq (giờ mở cửa, liên hệ, ...) ---
  {
    target: "faq",
    patterns: [
      "gio mo cua", "mo cua", "mo cua may gio", "mo toi may gio", "quan mo may gio",
      "lien he", "hotline", "so dien thoai", "sdt", "facebook", "fanpage",
      "dia chi", "cua hang", "thong tin", "co ship", "giao hang", "dong cua", "gio dong cua",
      "gio hoat dong", "lam viec may gio", "phuc vu may gio", "website", "instagram", "zalo",
      "email", "contact", "cham soc khach hang", "bao gio mo cua", "bao gio dong cua",
      "quan dong luc nao", "quan mo luc nao", "open", "close", "opening hours",
      "business hours", "working hours", "gio lam viec", "hotline la gi", "so hotline",
      "facebook cua quan", "fanpage cua quan", "zalo cua quan", "email cua quan",
    ],
    priority: 6,
  },
  // --- greeting ---
  {
    target: "greeting",
    patterns: [
      "xin chao", "chao", "chao ban", "chao shop", "chao quan", "hello", "hi", "oi", "alo", "helo",
      "hey", "good morning", "good afternoon", "good evening",
    ],
    priority: 10,
  },
];

/** Mapping: (action, target) -> intent_code. Specific targets first. */
export const INTENT_RULES: { action: Action | string; target: Target; intentCode: string; priority: number }[] = [
  { action: "greet", target: "greeting", intentCode: "greeting", priority: 100 },
  { action: "suggest", target: "coffee", intentCode: "coffee_recommendation", priority: 95 },
  { action: "view", target: "coffee", intentCode: "coffee_recommendation", priority: 90 },
  { action: "suggest", target: "freeze", intentCode: "freeze_recommendation", priority: 95 },
  { action: "view", target: "freeze", intentCode: "freeze_recommendation", priority: 90 },
  { action: "suggest", target: "tea", intentCode: "tea_recommendation", priority: 95 },
  { action: "view", target: "tea", intentCode: "tea_recommendation", priority: 90 },
  { action: "suggest", target: "phindi", intentCode: "phindi_recommendation", priority: 95 },
  { action: "view", target: "phindi", intentCode: "phindi_recommendation", priority: 90 },
  { action: "suggest", target: "juice", intentCode: "juice_recommendation", priority: 95 },
  { action: "view", target: "juice", intentCode: "juice_recommendation", priority: 90 },
  { action: "suggest", target: "others_drink", intentCode: "others_drink_recommendation", priority: 95 },
  { action: "view", target: "others_drink", intentCode: "others_drink_recommendation", priority: 90 },
  { action: "suggest", target: "bakery_savory", intentCode: "bakery_savory_recommendation", priority: 95 },
  { action: "view", target: "bakery_savory", intentCode: "bakery_savory_recommendation", priority: 90 },
  { action: "suggest", target: "bakery_sweet", intentCode: "bakery_sweet_recommendation", priority: 95 },
  { action: "view", target: "bakery_sweet", intentCode: "bakery_sweet_recommendation", priority: 90 },
  { action: "suggest", target: "bakery", intentCode: "bakery_recommendation", priority: 90 },
  { action: "view", target: "bakery", intentCode: "bakery_recommendation", priority: 85 },
  { action: "suggest", target: "topping", intentCode: "topping_recommendation", priority: 95 },
  { action: "view", target: "topping", intentCode: "topping_recommendation", priority: 90 },
  { action: "suggest", target: "drink", intentCode: "drink_recommendation", priority: 85 },
  { action: "view", target: "drink", intentCode: "drink_recommendation", priority: 80 },
  { action: "view", target: "menu", intentCode: "faq", priority: 90 },
  { action: "check", target: "menu", intentCode: "faq", priority: 90 },
  { action: "view", target: "order", intentCode: "order_status", priority: 90 },
  { action: "check", target: "order", intentCode: "order_status", priority: 90 },
  { action: "view", target: "promotion", intentCode: "promotion", priority: 85 },
  { action: "check", target: "promotion", intentCode: "promotion", priority: 85 },
  { action: "book_table", target: "reservation", intentCode: "reservation", priority: 85 },
  { action: "book", target: "reservation", intentCode: "reservation", priority: 85 },
  { action: "view", target: "reservation", intentCode: "reservation", priority: 80 },
  { action: "check", target: "reservation", intentCode: "reservation", priority: 80 },
  { action: "view", target: "table", intentCode: "table_availability", priority: 85 },
  { action: "check", target: "table", intentCode: "table_availability", priority: 85 },
  { action: "view", target: "nearest_store", intentCode: "nearest_store", priority: 85 },
  { action: "check", target: "nearest_store", intentCode: "nearest_store", priority: 85 },
  { action: "view", target: "drink_pairing_combo_and_cake", intentCode: "drink_pairing_combo_and_cake", priority: 95 },
  { action: "view", target: "drink_pairing_combo", intentCode: "drink_pairing_combo", priority: 95 },
  { action: "view", target: "drink_pairing_cake", intentCode: "drink_pairing_cake", priority: 95 },
  { action: "suggest", target: "combo_tea", intentCode: "combo_recommendation", priority: 95 },
  { action: "view", target: "combo_tea", intentCode: "combo_recommendation", priority: 95 },
  { action: "suggest", target: "combo_coffee", intentCode: "combo_recommendation", priority: 95 },
  { action: "view", target: "combo_coffee", intentCode: "combo_recommendation", priority: 95 },
  { action: "suggest", target: "combo_phindi", intentCode: "combo_recommendation", priority: 95 },
  { action: "view", target: "combo_phindi", intentCode: "combo_recommendation", priority: 95 },
  { action: "suggest", target: "combo", intentCode: "combo_recommendation", priority: 90 },
  { action: "view", target: "combo", intentCode: "combo_recommendation", priority: 90 },
  { action: "view", target: "points", intentCode: "faq", priority: 85 },
  { action: "check", target: "points", intentCode: "faq", priority: 85 },
  { action: "view", target: "faq", intentCode: "faq", priority: 80 },
];
