import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authApi } from '../api/auth.api';
import { useAuthStore } from '../../../app/store/auth.store';

export default function AccountRegisterPage() {
  const navigate = useNavigate(); const setTokensAndUser = useAuthStore((s) => s.setTokensAndUser);
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [phone, setPhone] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const session = await authApi.registerAccount({ fullName, email, password, phone: phone || undefined }); setTokensAndUser(session.accessToken, session.refreshToken, session.user); navigate('/workspace/select-tenant', { replace: true }); } catch (e: any) { setError(e?.response?.data?.message || 'Không thể tạo tài khoản KONEKT.'); } finally { setSaving(false); } };
  return <main style={{ maxWidth: 480, margin: '64px auto', padding: 24, color: '#2A3B2C' }}><p style={{ color: '#687668' }}>KONEKT / Tài khoản toàn cục</p><h1>Tạo tài khoản KONEKT</h1><p>Tạo một tài khoản trước, sau đó bạn có thể mở doanh nghiệp hoặc tham gia doanh nghiệp bằng mã KON-…</p><form onSubmit={submit} style={{ display: 'grid', gap: 14, marginTop: 24 }}><label>Họ tên<input required value={fullName} onChange={(e) => setFullName(e.target.value)} style={{ width: '100%', padding: 10, boxSizing: 'border-box' }} /></label><label>Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} style={{ width: '100%', padding: 10, boxSizing: 'border-box' }} /></label><label>Mật khẩu<input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} style={{ width: '100%', padding: 10, boxSizing: 'border-box' }} /></label><label>Số điện thoại (tuỳ chọn)<input value={phone} onChange={(e) => setPhone(e.target.value)} style={{ width: '100%', padding: 10, boxSizing: 'border-box' }} /></label>{error && <p style={{ color: '#9F2F2D' }}>{error}</p>}<button disabled={saving} style={{ padding: 12, background: '#364D39', color: '#FAF6F3', border: 0, borderRadius: 6 }}>{saving ? 'Đang tạo…' : 'Tạo tài khoản KONEKT'}</button></form><p><Link to="/login">Đã có tài khoản? Đăng nhập</Link></p></main>;
}
