/**
 * Danh sách thành phố/tỉnh Việt Nam (phục vụ chọn địa chỉ)
 */
export const CITY_OPTIONS: string[] = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Đà Nẵng",
  "Hải Phòng",
  "Cần Thơ",
  "Biên Hòa",
  "Nha Trang",
  "Huế",
  "Đà Lạt",
  "Vũng Tàu",
  "Buôn Ma Thuột",
  "Quy Nhơn",
  "Thanh Hóa",
  "Việt Trì",
  "Hạ Long",
  "Pleiku",
  "Thủ Dầu Một",
  "Bắc Ninh",
  "Hải Dương",
  "Nam Định",
  "Vinh",
  "Thái Nguyên",
  "Rạch Giá",
  "Long Xuyên",
  "Mỹ Tho",
  "Cà Mau",
  "Bến Tre",
  "Vĩnh Long",
  "Trà Vinh",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cần Giờ",
  "Hà Giang",
  "Cao Bằng",
  "Lạng Sơn",
  "Lào Cai",
  "Sơn La",
  "Điện Biên",
  "Lai Châu",
];
